"""empty message

Revision ID: 09bee9526080
Revises: bd76967127d0
Create Date: 2019-02-20 20:40:38.894676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bee9526080'
down_revision = 'bd76967127d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verification_hash', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verification_hash')
    # ### end Alembic commands ###
