"""gallery table

Revision ID: 100fdf4708d2
Revises: dc85a82292f6
Create Date: 2019-01-29 03:53:12.181663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100fdf4708d2'
down_revision = 'dc85a82292f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery')
    # ### end Alembic commands ###
