"""1.0

Revision ID: 104c85f91fda
Revises: 504e573da6ec
Create Date: 2019-02-12 21:53:18.474728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104c85f91fda'
down_revision = '504e573da6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('store', sa.Column('quantity', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
