"""empty message

Revision ID: 168dd29b3bf2
Revises: 2f9dfdf164de
Create Date: 2019-10-01 23:09:28.365021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168dd29b3bf2'
down_revision = '2f9dfdf164de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blog_comment', 'blog', ['blog_of_comment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    # ### end Alembic commands ###
