"""empty message

Revision ID: 1fa2c662d7aa
Revises: b63a0b985ae9
Create Date: 2019-07-28 19:26:34.738405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa2c662d7aa'
down_revision = 'b63a0b985ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_ids_purchased', sa.String(length=40), nullable=True),
    sa.Column('total_paid', sa.Integer(), nullable=True),
    sa.Column('billing_name', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.String(length=30), nullable=True),
    sa.Column('billing_city', sa.String(length=20), nullable=True),
    sa.Column('billing_province', sa.String(length=20), nullable=True),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=True),
    sa.Column('billing_phone_number', sa.String(length=20), nullable=True),
    sa.Column('billing_email', sa.String(length=20), nullable=True),
    sa.Column('date_receipt_generated', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_receipt')
    # ### end Alembic commands ###
