"""empty message

Revision ID: 25580e619a9c
Revises: 94eec7d649f6
Create Date: 2019-03-26 21:40:38.852894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25580e619a9c'
down_revision = '94eec7d649f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_concert_booking')
    op.drop_table('concert_booking')
    op.add_column('concert_seats', sa.Column('customer_email', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert_seats', 'customer_email')
    op.create_table('concert_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_of_purchase', sa.VARCHAR(length=120), nullable=True),
    sa.Column('concert_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_concert_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_of_issue', sa.VARCHAR(length=120), nullable=True),
    sa.Column('row', sa.VARCHAR(length=10), nullable=True),
    sa.Column('seat', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ticket_hash', sa.VARCHAR(length=100), nullable=True),
    sa.Column('concert_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
