"""empty message

Revision ID: 279237b7749d
Revises: 168dd29b3bf2
Create Date: 2019-10-01 23:11:06.715068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279237b7749d'
down_revision = '168dd29b3bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('date_posted', sa.VARCHAR(length=120), nullable=True),
    sa.Column('reply', sa.INTEGER(), nullable=True),
    sa.Column('reply_to', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('blog_of_comment', sa.INTEGER(), nullable=True),
    sa.Column('first_name_of_commenter', sa.VARCHAR(length=40), nullable=True),
    sa.Column('last_name_of_commenter', sa.VARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['reply_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
