"""empty message

Revision ID: 2c2f4cfe736e
Revises: 81f4c7d6da6b
Create Date: 2019-07-25 13:55:59.607748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2f4cfe736e'
down_revision = '81f4c7d6da6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert_seats', sa.Column('attended', sa.Integer(), nullable=True))
    op.add_column('concert_seats', sa.Column('date_attended', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert_seats', 'date_attended')
    op.drop_column('concert_seats', 'attended')
    # ### end Alembic commands ###
