"""empty message

Revision ID: 2f9dfdf164de
Revises: f867f07d830d
Create Date: 2019-10-01 23:08:58.267555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9dfdf164de'
down_revision = 'f867f07d830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('first_name_of_commenter', sa.String(length=40), nullable=True))
    op.add_column('blog_comment', sa.Column('last_name_of_commenter', sa.String(length=40), nullable=True))
    op.alter_column('blog_comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'blog_comment', 'blog', ['blog_of_comment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    op.alter_column('blog_comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('blog_comment', 'last_name_of_commenter')
    op.drop_column('blog_comment', 'first_name_of_commenter')
    # ### end Alembic commands ###
