"""empty message

Revision ID: 33451abec269
Revises: e54e03e27913
Create Date: 2019-03-04 16:10:36.026857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33451abec269'
down_revision = 'e54e03e27913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date_of_purchase', sa.String(length=120), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.String(length=10), nullable=True),
    sa.Column('row', sa.String(length=10), nullable=True),
    sa.Column('filled', sa.Integer(), nullable=True),
    sa.Column('filled_by_customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['filled_by_customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_seats')
    op.drop_table('concert_booking')
    # ### end Alembic commands ###
