"""fixes

Revision ID: 590ca21fdbd5
Revises: ab4ded39755e
Create Date: 2019-02-12 21:46:03.291897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590ca21fdbd5'
down_revision = 'ab4ded39755e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_description'), table_name='blog')
    # ### end Alembic commands ###
