"""empty message

Revision ID: 61d6d329614e
Revises: 09bee9526080
Create Date: 2019-02-25 00:25:58.182069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d6d329614e'
down_revision = '09bee9526080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'active')
    # ### end Alembic commands ###
