"""modified failedlogins

Revision ID: 6f04c982383c
Revises: ae08b7574d43
Create Date: 2019-01-29 18:25:02.967449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f04c982383c'
down_revision = 'ae08b7574d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failed_logins', sa.Column('attempted_username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failed_logins', 'attempted_username')
    # ### end Alembic commands ###
