"""empty message

Revision ID: 75d837663ac0
Revises: 41e3410b11b4
Create Date: 2019-02-03 02:15:06.381772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d837663ac0'
down_revision = '41e3410b11b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('description', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_blog_description'), 'blog', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_description'), table_name='blog')
    op.drop_column('blog', 'description')
    # ### end Alembic commands ###
