"""empty message

Revision ID: 7c6fedaa28b3
Revises: f0eae4367aa9
Create Date: 2019-03-05 00:03:04.638125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6fedaa28b3'
down_revision = 'f0eae4367aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert_seats', sa.Column('concert_name', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert_seats', 'concert_name')
    # ### end Alembic commands ###
