"""empty message

Revision ID: 81f4c7d6da6b
Revises: 25580e619a9c
Create Date: 2019-04-18 14:58:04.099570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f4c7d6da6b'
down_revision = '25580e619a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('forgot_username_stamp', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('forgot_username_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'forgot_username_token')
    op.drop_column('user', 'forgot_username_stamp')
    # ### end Alembic commands ###
