"""location column

Revision ID: 8be9344b4d8b
Revises: bef68bf027c5
Create Date: 2019-02-20 18:04:03.553838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be9344b4d8b'
down_revision = 'bef68bf027c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'location')
    # ### end Alembic commands ###
