"""updates from vms-simple

Revision ID: 941a9bcbc1ff
Revises: 472b4f9cd2cd
Create Date: 2019-09-01 10:17:37.572328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941a9bcbc1ff'
down_revision = '472b4f9cd2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column', sa.String(length=64), nullable=True),
    sa.Column('picture_associated', sa.String(length=128), nullable=True),
    sa.Column('title_associated', sa.String(length=128), nullable=True),
    sa.Column('text_associated', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_page')
    # ### end Alembic commands ###
