"""verision 2.0

Revision ID: 94eec7d649f6
Revises: c148448e0286
Create Date: 2019-03-26 21:37:36.098619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94eec7d649f6'
down_revision = 'c148448e0286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('date_of_purchase', sa.String(length=120), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_concert_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('date_of_issue', sa.String(length=120), nullable=True),
    sa.Column('row', sa.String(length=10), nullable=True),
    sa.Column('seat', sa.String(length=10), nullable=True),
    sa.Column('ticket_hash', sa.String(length=100), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('concertshop', 'quantity')
    op.drop_column('concertshop', 'quantity_left')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concertshop', sa.Column('quantity_left', sa.VARCHAR(length=50), nullable=True))
    op.add_column('concertshop', sa.Column('quantity', sa.VARCHAR(length=50), nullable=True))
    op.drop_table('custom_concert_booking')
    op.drop_table('concert_booking')
    # ### end Alembic commands ###
