"""updated users

Revision ID: 95fb0f36e0eb
Revises: 6f04c982383c
Create Date: 2019-01-30 00:06:12.694492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fb0f36e0eb'
down_revision = '6f04c982383c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authority')
    # ### end Alembic commands ###
