"""FailedLogins Table

Revision ID: ae08b7574d43
Revises: 100fdf4708d2
Create Date: 2019-01-29 17:45:34.333590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae08b7574d43'
down_revision = '100fdf4708d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=256), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_logins')
    # ### end Alembic commands ###
