"""empty message

Revision ID: b63a0b985ae9
Revises: 2c2f4cfe736e
Create Date: 2019-07-25 14:50:18.209667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63a0b985ae9'
down_revision = '2c2f4cfe736e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concertshop', sa.Column('time_of_event', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concertshop', 'time_of_event')
    # ### end Alembic commands ###
