"""empty message

Revision ID: c10baa35a1e1
Revises: f96b4db7f282
Create Date: 2019-09-03 00:27:34.841124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10baa35a1e1'
down_revision = 'f96b4db7f282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concert_seats', sa.Column('price_paid', sa.String(length=20), nullable=True))
    op.add_column('concert_seats', sa.Column('type_of_seat_bought', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concert_seats', 'type_of_seat_bought')
    op.drop_column('concert_seats', 'price_paid')
    # ### end Alembic commands ###
