"""empty message

Revision ID: c148448e0286
Revises: 7c6fedaa28b3
Create Date: 2019-03-26 17:31:36.767011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c148448e0286'
down_revision = '7c6fedaa28b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_booking')
    op.add_column('concert_seats', sa.Column('date_of_purchase', sa.String(length=120), nullable=True))
    op.add_column('concert_seats', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('concert_seats', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('concert_seats', sa.Column('ticket_hash', sa.String(length=100), nullable=True))
    op.drop_column('concertshop', 'quantity')
    op.drop_column('concertshop', 'quantity_left')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concertshop', sa.Column('quantity_left', sa.VARCHAR(length=50), nullable=True))
    op.add_column('concertshop', sa.Column('quantity', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('concert_seats', 'ticket_hash')
    op.drop_column('concert_seats', 'last_name')
    op.drop_column('concert_seats', 'first_name')
    op.drop_column('concert_seats', 'date_of_purchase')
    op.create_table('concert_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('date_of_purchase', sa.VARCHAR(length=120), nullable=True),
    sa.Column('concert_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
