"""concertseats and concertbooking

Revision ID: d24570a772b5
Revises: 87eebf4d8c1a
Create Date: 2019-03-04 16:04:48.274127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24570a772b5'
down_revision = '87eebf4d8c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concertshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('concert_title', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('quantity_left', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('image_associated', sa.String(length=120), nullable=True),
    sa.Column('date_of_event', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date_of_purchase', sa.String(length=120), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.String(length=10), nullable=True),
    sa.Column('row', sa.String(length=10), nullable=True),
    sa.Column('filled', sa.Integer(), nullable=True),
    sa.Column('filled_by_customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['filled_by_customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('concert_shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_shop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.INTEGER(), nullable=True),
    sa.Column('concert_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity_left', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image_associated', sa.VARCHAR(length=120), nullable=True),
    sa.Column('date_of_event', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('concert_seats')
    op.drop_table('concert_booking')
    op.drop_table('concertshop')
    # ### end Alembic commands ###
