"""1.0.1

Revision ID: d4d6e1f0b727
Revises: 104c85f91fda
Create Date: 2019-02-12 21:54:39.370639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d6e1f0b727'
down_revision = '104c85f91fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('store', sa.Column('quantity_left', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
