"""empty message

Revision ID: e54e03e27913
Revises: d24570a772b5
Create Date: 2019-03-04 16:10:13.820910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54e03e27913'
down_revision = 'd24570a772b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_seats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('date_of_purchase', sa.VARCHAR(length=120), nullable=True),
    sa.Column('concert_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_seats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('concert_id', sa.INTEGER(), nullable=False),
    sa.Column('seat', sa.VARCHAR(length=10), nullable=True),
    sa.Column('row', sa.VARCHAR(length=10), nullable=True),
    sa.Column('filled', sa.INTEGER(), nullable=True),
    sa.Column('filled_by_customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['concert_id'], ['concertshop.id'], ),
    sa.ForeignKeyConstraint(['filled_by_customer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
