"""empty message

Revision ID: f0eae4367aa9
Revises: 33451abec269
Create Date: 2019-03-04 23:23:46.708107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0eae4367aa9'
down_revision = '33451abec269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
