"""empty message

Revision ID: f7e198be8a0a
Revises: 279237b7749d
Create Date: 2019-10-01 23:11:37.675604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e198be8a0a'
down_revision = '279237b7749d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('first_name_of_commenter', sa.String(length=40), nullable=True),
    sa.Column('last_name_of_commenter', sa.String(length=40), nullable=True),
    sa.Column('date_posted', sa.String(length=120), nullable=True),
    sa.Column('reply', sa.Integer(), nullable=True),
    sa.Column('blog_of_comment', sa.Integer(), nullable=True),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_of_comment'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['reply_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_comment')
    # ### end Alembic commands ###
