"""empty message

Revision ID: f867f07d830d
Revises: c10baa35a1e1
Create Date: 2019-10-01 22:22:27.206736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f867f07d830d'
down_revision = 'c10baa35a1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=124), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog_comment', sa.Column('blog_of_comment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_comment', 'blog', ['blog_of_comment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_comment', type_='foreignkey')
    op.drop_column('blog_comment', 'blog_of_comment')
    op.drop_table('one_time_link')
    # ### end Alembic commands ###
