"""empty message

Revision ID: f96b4db7f282
Revises: 594e3299e350
Create Date: 2019-09-02 20:58:15.255381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96b4db7f282'
down_revision = '594e3299e350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concertshop', sa.Column('children_price', sa.String(length=20), nullable=True))
    op.add_column('concertshop', sa.Column('senior_price', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concertshop', 'senior_price')
    op.drop_column('concertshop', 'children_price')
    # ### end Alembic commands ###
